version: '2'
services:

    zoo4:
        image: zookeeper
        restart: always
        container_name: zoo4
        ports:
            - "12184:2181"
        volumes:
            - .:/run
            - ./data1:/data
        environment:
            ZOO_MY_ID: 4
            ZOO_SERVERS: server.4=zoo4:2888:3888 server.5=zoo5:2888:3888 server.6=zoo6:2888:3888
        entrypoint: /run/docker-entrypoint_2.sh
        command: zkServer.sh start-foreground
        #depends_on:
        #    - zoo3

    zoo5:
        image: zookeeper
        restart: always
        container_name: zoo5
        ports:
            - "12185:2181"
        volumes:
            - .:/run
            - ./data2:/data
        environment:
            ZOO_MY_ID: 5
            ZOO_SERVERS: server.4=zoo4:2888:3888 server.5=zoo5:2888:3888 server.6=zoo6:2888:3888
        entrypoint: /run/docker-entrypoint_2.sh
        command: zkServer.sh start-foreground
        depends_on:
            - zoo4

    zoo6:
        image: zookeeper
        restart: always
        container_name: zoo6
        ports:
            - "12186:2181"
        volumes:
            - .:/run
            - ./data3:/data
        environment:
            ZOO_MY_ID: 6
            ZOO_SERVERS: server.4=zoo4:2888:3888 server.5=zoo5:2888:3888 server.6=zoo6:2888:3888
        entrypoint: /run/docker-entrypoint_2.sh
        command: zkServer.sh start-foreground
        depends_on:
            - zoo5

networks:
    default:
        external:
            name: Net9588
