version: '2'
services:
    zoo1:
        image: zookeeper
        restart: always
        container_name: zoo1
        ports:
            - "12181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 server.4=zoo4:2888:3888:observer server.5=zoo5:2888:3888:observer server.6=zoo6:2888:3888:observer

    zoo2:
        image: zookeeper
        restart: always
        container_name: zoo2
        ports:
            - "12182:2181"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 server.4=zoo4:2888:3888:observer server.5=zoo5:2888:3888:observer server.6=zoo6:2888:3888:observer
        depends_on:
            - zoo1

    zoo3:
        image: zookeeper
        restart: always
        container_name: zoo3
        ports:
            - "12183:2181"
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 server.4=zoo4:2888:3888:observer server.5=zoo5:2888:3888:observer server.6=zoo6:2888:3888:observer
        depends_on:
            - zoo2

networks:
    default:
        external:
            name: Net9588
